### ISSUE TITLE
Avoid the python prompt in some cells?

### ISSUE THREAD

**Issue by FrancescAlted** [matthew-brett/nb2plots#7]
Hi.  I am starting to use `nb2plots` and I generally like it.  I have a question though.  Is there a way to get code cells rendered without the python prompts (`>>>` and `...`)?

For example, when I use this cell:

```
%%writefile myconf.yaml
root_dir: FPSIM
input_format: namelist
releases:
    tstart: "2015-01-01"
    tend: "2017-01-01"
    freq: 3H
    emissions:
        class: Station
        comment_prefix: Finse
        release_type: point
        release_point:
            lat: 60.594
            lon: 7.527
            elv: 1210.

```

It gets rendered as:

![image](https://user-images.githubusercontent.com/314521/35862137-c76bc66c-0b4a-11e8-9fb1-dea2e99f89d4.png)

which is not what I want.  In fact, the notebook renders it like:

![image](https://user-images.githubusercontent.com/314521/35862200-1240861e-0b4b-11e8-98d0-e049fa22ce0b.png)

which is closer to what I want. Hints?

**Comment by matthew-brett** [comment]
I'm afraid this is a fundamental limitation of nb2plots, at the moment.  It converts all code cells to doctest format code blocks, and pays no attention to things like magics.  So, in practice, you can't make this cell executable from the nb2plots .rst file, or convert it to an executable cell when rebuilding the notebook.

For now, what I would do, is work out some other way that doesn't use the magic, maybe something like:

```
# Write the myconf.yaml file.
open('myconf.yaml', 'wt') as fobj: fobj.write("""\
root_dir: FPSIM
input_format: namelist
releases:
    tstart: "2015-01-01"
    tend: "2017-01-01"
    freq: 3H
    emissions:
        class: Station
        comment_prefix: Finse
        release_type: point
        release_point:
            lat: 60.594
            lon: 7.527
""")
```

I'm in the process of thinking how to preserve the notebook cell contents in the .rst document, and use the Jupyter machinery to execute the cells, and return the output, but I haven't started that yet.  I'm hoping to get that done in the next few weeks, but no promises.
